
#######################
# away_mode
#######################

- alias: turn on the vacuum when away
  trigger:
    platform: template
    value_template: "{{ is_state_attr('climate.hallway', 'away_mode', 'on') }}"
  action:
    service: vacuum.turn_on
    entity_id: vacuum.consuela


- alias: turn off the bedroom light when away
  trigger:
    platform: template
    value_template: "{{ is_state_attr('climate.hallway', 'away_mode', 'on') }}"
  action:
    service: light.turn_off
    entity_id: light.master_bedroom


# - alias: turn off the vacuum when home
#   trigger:
#     platform: template
#     value_template: "{{ is_state_attr('climate.hallway', 'away_mode', 'off') }}"
#   action:
#     - service: vacuum.stop
#       entity_id: vacuum.consuela
#     - service: vacuum.return_to_base
#       entity_id: vacuum.consuela

#######################
# time
#######################

# - alias: fade on bedroom light on weekdays at 6:30am
#   trigger:
#     - platform: time
#       at: '6:30:00'
#   condition:
#     - condition: time
#       weekday:
#         - mon
#         - tue
#         - wed
#         - thu
#         - fri
#   action:
#     - service: light.turn_on
#       data:
#         entity_id:
#           - light.master_bedroom
#         profile: energize
#         transition: 900


# - alias: turn on outside lights on weekdays at 6:30am
#   trigger:
#     - platform: time
#       at: '6:30:00'
#   condition:
#     - condition: time
#       weekday:
#         - mon
#         - tue
#         - wed
#         - thu
#         - fri
#   action:
#     - service: light.turn_on
#       data:
#         entity_id:
#           - light.living_room
#           - light.outside
#         profile: energize


# - alias: turn off outside lights at 11pm
#   trigger:
#     - platform: time
#       at: '23:00:00'
#   action:
#     - service: light.turn_off
#       data:
#         entity_id:
#           - light.living_room
#           - light.outside


#######################
# sun
#######################


# - alias: turn off outside lights at sunrise
#   trigger:
#     - platform: sun
#       event: sunrise
#   action:
#     - service: light.turn_off
#       data:
#         entity_id:
#           - light.living_room
#           - light.outside


# - alias: turn on outside lights at sunset
#   trigger:
#     - platform: sun
#       event: sunset
#   action:
#     - service: light.turn_on
#       data:
#         entity_id:
#           - light.living_room
#           - light.outside
#         profile: read


#######################
# motion
#######################

- alias: turn on family room light when movement detected
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_camera_motion_detected
    to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: light.family_room

- alias: turn off family room light 20 minutes after last movement detected
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_camera_motion_detected
    to: 'off'
    for:
      minutes: 20
  action:
    service: homeassistant.turn_off
    entity_id: light.family_room