
#######################
# home and away
#######################


- alias: turn on vacuum when away
  trigger:
    - platform: state
      entity_id: sensor.away_mode
      from: 'off'
      to: 'on'
  action:
    - service: vacuum.turn_on
      entity_id: vacuum.consuela


- alias: turn off vacuum when home
  trigger:
    - platform: state
      entity_id: sensor.away_mode
      from: 'on'
      to: 'off'
  action:
    - service: vacuum.stop
      entity_id: vacuum.consuela
    - service: vacuum.return_to_base
      entity_id: vacuum.consuela


- alias: turn off lights when away
  trigger:
    - platform: state
      entity_id: sensor.away_mode
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.master_bedroom
          - light.living_room
          - light.family_room


- alias: turn on lights when home
  trigger:
    - platform: state
      entity_id: sensor.away_mode
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: light.turn_on
      data_template:
        profile: concentrate
        entity_id:
          - light.outside
    - service: light.turn_on
      data_template:
        profile: "{{ states('sensor.preferred_light_profile') }}"
        entity_id:
          - light.family_room
          - light.living_room


#######################
# auto-apply profiles
#######################


- alias: change living_room light profile
  trigger:
    - platform: state
      entity_id: light.living_room
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.next_sun_event
  condition:
    - condition: state
      entity_id: light.living_room
      state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.living_room
        profile: "{{ states('sensor.preferred_light_profile') }}"


- alias: change family_room light profile
  trigger:
    - platform: state
      entity_id: light.family_room
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.next_sun_event
  condition:
    - condition: state
      entity_id: light.family_room
      state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.family_room
        profile: "{{ states('sensor.preferred_light_profile') }}"


- alias: change master_bedroom light profile
  trigger:
    - platform: state
      entity_id: light.master_bedroom
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.next_sun_event
  condition:
    - condition: state
      entity_id: light.master_bedroom
      state: 'on'
    - condition: numeric_state
      entity_id: light.master_bedroom
      value_template: '{{ states.light.master_bedroom.attributes.brightness }}'
      above: 100
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.master_bedroom
        color_temp: "{{ states('sensor.preferred_light_color_temp') }}"
        brightness: "{{ states('sensor.preferred_light_brightness') }}"


#######################
# wake up on weekdays
#######################


- alias: fade on lights weekdays at 6:30am
  trigger:
    platform: time
    at: '6:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_on
      data:
        entity_id: light.master_bedroom
        color_temp: "{{ states('sensor.preferred_light_color_temp') }}"
        brightness: 1
    - delay:
        seconds: 1
    - service: light.turn_on
      data:
        entity_id: light.master_bedroom
        color_temp: "{{ states('sensor.preferred_light_color_temp') }}"
        brightness: "{{ states('sensor.preferred_light_brightness') }}"
        transition: 300


#######################
# sunrise and sunset
#######################

# schedule example:
# dawn     : 6:48 am
# rising   : 7:19 am
# +1 hr    : 8:19 am
# noon     : 12:17 pm
# -1 hr    : 4:14 pm
# setting  : 5:14 pm
# dusk     : 5:45 pm
# midnight : 12:17 am

- alias: turn on lights at dawn
  trigger:
    - platform: state
      entity_id: sensor.next_sun_event
      from: 'dawn'
  action:
    - service: light.turn_on
      data_template:
        profile: concentrate
        entity_id:
          - light.outside
    - service: light.turn_on
      data_template:
        profile: "{{ states('sensor.preferred_light_profile') }}"
        entity_id:
          - light.family_room
          - light.living_room


- alias: turn off lights after sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: "+01:00:00"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.family_room
          - light.living_room
          - light.outside
          - light.master_bedroom


- alias: turn on lights before sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  action:
    - service: light.turn_on
      data_template:
        profile: concentrate
        entity_id:
          - light.outside
    - service: light.turn_on
      data_template:
        profile: "{{ states('sensor.preferred_light_profile') }}"
        entity_id:
          - light.family_room
          - light.living_room


- alias: turn off lights at midnight
  trigger:
    - platform: state
      entity_id: sensor.next_sun_event
      from: 'midnight'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.family_room
          - light.living_room
          - light.outside