
#######################
# vacuum when away
#######################


- alias: turn on vacuum when away
  trigger:
    platform: state
    entity_id: sensor.away_mode
    from: 'off'
    to: 'on'
  action:
    service: vacuum.turn_on
    entity_id: vacuum.consuela


- alias: turn off vacuum when home
  trigger:
    platform: state
    entity_id: sensor.away_mode
    from: 'on'
    to: 'off'
  action:
    - service: vacuum.stop
      entity_id: vacuum.consuela
    - service: vacuum.return_to_base
      entity_id: vacuum.consuela


#######################
# lights when away
#######################


- alias: turn off lights when away
  trigger:
    platform: state
    entity_id: sensor.away_mode
    from: 'off'
    to: 'on'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.master_bedroom
        - light.living_room
        - light.family_room


- alias: turn on lights when home
  trigger:
    platform: state
    entity_id: sensor.away_mode
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: light.turn_on
    data_template:
      entity_id:
        - light.living_room
        - light.family_room
        - light.outside
      profile: >
        {% if now().hour >= 6 and now().hour < 12 %}
        energize
        {% elif now().hour >= 12 and now().hour < 18 %}
        concentrate
        {% elif now().hour >= 18 and now().hour < 24 %}
        read
        {% else %}
        relax
        {% endif %}


#######################
# time of day profiles
#######################


- alias: change outside light profile
  trigger:
    - platform: state
      entity_id: light.outside
      from: 'off'
      to: 'on'
    - platform: time
      at: '0:00:00'
    - platform: time
      at: '6:00:00'
    - platform: time
      at: '12:00:00'
    - platform: time
      at: '18:00:00'
  condition:
    condition: state
    entity_id: light.outside
    state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: light.outside
      # brightness: '{{states.light.outside.attributes.brightness}}'
      profile: >
        {%- if now().hour >= 6 and now().hour < 12 %}
        energize
        {% elif now().hour >= 12 and now().hour < 18 %}
        concentrate
        {% elif now().hour >= 18 and now().hour < 24 %}
        read
        {% else %}
        relax
        {% endif %}


- alias: change living_room light profile
  trigger:
    - platform: state
      entity_id: light.living_room
      from: 'off'
      to: 'on'
    - platform: time
      at: '0:00:00'
    - platform: time
      at: '6:00:00'
    - platform: time
      at: '12:00:00'
    - platform: time
      at: '18:00:00'
  condition:
    condition: state
    entity_id: light.living_room
    state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: light.living_room
      # brightness: '{{states.light.living_room.attributes.brightness}}'
      profile: >
        {%- if now().hour >= 6 and now().hour < 12 %}
        energize
        {% elif now().hour >= 12 and now().hour < 18 %}
        concentrate
        {% elif now().hour >= 18 and now().hour < 24 %}
        read
        {% else %}
        relax
        {% endif %}


- alias: change family_room light profile
  trigger:
    - platform: state
      entity_id: light.family_room
      from: 'off'
      to: 'on'
    - platform: time
      at: '0:00:00'
    - platform: time
      at: '6:00:00'
    - platform: time
      at: '12:00:00'
    - platform: time
      at: '18:00:00'
  condition:
    condition: state
    entity_id: light.family_room
    state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: light.family_room
      # brightness: '{{states.light.family_room.attributes.brightness}}'
      profile: >
        {%- if now().hour >= 6 and now().hour < 12 %}
        energize
        {% elif now().hour >= 12 and now().hour < 18 %}
        concentrate
        {% elif now().hour >= 18 and now().hour < 24 %}
        read
        {% else %}
        relax
        {% endif %}


# - alias: change master_bedroom light profile
#   trigger:
#     - platform: state
#       entity_id: light.master_bedroom
#       from: 'off'
#       to: 'on'
#     - platform: time
#       at: '0:00:00'
#     - platform: time
#       at: '6:00:00'
#     - platform: time
#       at: '12:00:00'
#     - platform: time
#       at: '18:00:00'
#   condition:
#     condition: state
#     entity_id: light.master_bedroom
#     state: 'on'
#   action:
#     service: light.turn_on
#     data_template:
#       entity_id: light.master_bedroom
#       brightness: '{{states.light.master_bedroom.attributes.brightness}}'
#       profile: >
#         {%- if now().hour >= 6 and now().hour < 12 %}
#         energize
#         {% elif now().hour >= 12 and now().hour < 18 %}
#         concentrate
#         {% elif now().hour >= 18 and now().hour < 24 %}
#         read
#         {% else %}
#         relax
#         {% endif %}


#######################
# wake and sleep
#######################


- alias: fade on lights weekdays at 6:30am
  trigger:
    platform: time
    at: '6:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.master_bedroom
        profile: relax
        brightness: 1
    - delay:
        seconds: 1
    - service: light.turn_on
      data:
        entity_id:
          - light.master_bedroom
        profile: energize
        brightness: 254
        transition: 900


- alias: turn on lights weekdays at 6:30am
  trigger:
    platform: time
    at: '6:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.family_room
          - light.living_room
          - light.outside
        profile: energize


- alias: turn off lights at 11pm
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.family_room
        - light.living_room
        - light.outside


#######################
# sunrise and sunset
#######################


- alias: turn off lights after sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:30:00" 
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.family_room
        - light.living_room
        - light.outside


- alias: turn on lights before sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00" 
  action:
    service: light.turn_on
    data_template:
      entity_id:
        - light.family_room
        - light.living_room
        - light.outside
      profile: >
        {% if now().hour >= 6 and now().hour < 12 %}
        energize
        {% elif now().hour >= 12 and now().hour < 18 %}
        concentrate
        {% elif now().hour >= 18 and now().hour < 24 %}
        read
        {% else %}
        relax
        {% endif %}


#######################
# motion and no motion
#######################


# - alias: turn on lights when motion detected
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.kitchen_camera_motion_detected
#       to: 'on'
#     - platform: state
#       entity_id: binary_sensor.kitchen_camera_sound_detected
#       to: 'on'
#     - platform: state
#       entity_id: binary_sensor.kitchen_camera_person_detected
#       to: 'on'
#   condition:
#     # - condition: state
#     #   entity_id: sensor.away_mode
#     #   state: 'on'
#     # - condition: state
#     #   entity_id: sun.sun
#     #   state: 'below_horizon'
#     condition: state
#     entity_id: light.family_room
#     state: 'off'
#   action:
#     service: light.turn_on
#     data_template:
#       entity_id:
#         - light.family_room
#       profile: >
#         {% if now().hour >= 6 and now().hour < 12 %}
#         energize
#         {% elif now().hour >= 12 and now().hour < 18 %}
#         concentrate
#         {% elif now().hour >= 18 and now().hour < 24 %}
#         read
#         {% else %}
#         relax
#         {% endif %}


# - alias: turn off lights after last motion detected
#   trigger:
#     platform: time
#     minutes: '/5' # check every 5 min
#     seconds: 00
#   condition:
#     # - condition: state
#     #   entity_id: sensor.away_mode
#     #   state: 'on'
#     - condition: state
#       entity_id: light.family_room
#       state: 'on'
#       for:
#         minutes: 60 # only if light on for 60 min
#     - condition: state
#       entity_id: binary_sensor.kitchen_camera_motion_detected
#       state: 'off'
#       for:
#         minutes: 60 # only if no motion for for 60 min
#     - condition: state
#       entity_id: binary_sensor.kitchen_camera_sound_detected
#       state: 'off'
#       for:
#         minutes: 60 # only if no sound for for 60 min
#     - condition: state
#       entity_id: binary_sensor.kitchen_camera_person_detected
#       state: 'off'
#       for:
#         minutes: 60 # only if no person for for 60 min
#   action:
#     service: light.turn_off
#     data:
#       entity_id:
#         - light.family_room
