
#######################
# home and away
#######################


- alias: turn on vacuum when away
  trigger:
    - platform: state
      entity_id: sensor.away_mode
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: vacuum.consuela
      state: 'off'
  action:
    - service: vacuum.turn_on
      entity_id: vacuum.consuela


# - alias: turn off vacuum when home
#   trigger:
#     - platform: state
#       entity_id: sensor.away_mode
#       from: 'on'
#       to: 'off'
#   condition:
#     - condition: state
#       entity_id: vacuum.consuela
#       state: 'on'
#   action:
#     - service: vacuum.turn_off
#       entity_id: vacuum.consuela


- alias: turn off lights when away
  trigger:
    - platform: state
      entity_id: sensor.away_mode
      from: 'off'
      to: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.master_bedroom
          - light.living_room
          - light.family_room


- alias: turn on lights when home
  trigger:
    - platform: state
      entity_id: sensor.away_mode
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: light.turn_on
      data_template:
        profile: "{{ states('sensor.preferred_light_profile') }}"
        entity_id:
          - light.family_room
          - light.living_room
          - light.outside


#######################
# light profiles
#######################


- alias: change outside light profile
  trigger:
    - platform: state
      entity_id: light.outside
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.next_sun_event
  condition:
    - condition: state
      entity_id: light.outside
      state: 'on'
    - condition: numeric_state
      entity_id: light.outside
      value_template: '{{ states.light.outside.attributes.brightness }}'
      above: 100
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.outside
        profile: "{{ states('sensor.preferred_light_profile') }}"


- alias: change living_room light profile
  trigger:
    - platform: state
      entity_id: light.living_room
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.next_sun_event
  condition:
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - condition: numeric_state
      entity_id: light.living_room
      value_template: '{{ states.light.living_room.attributes.brightness }}'
      above: 100
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.living_room
        profile: "{{ states('sensor.preferred_light_profile') }}"


- alias: change family_room light profile
  trigger:
    - platform: state
      entity_id: light.family_room
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.next_sun_event
  condition:
    - condition: state
      entity_id: light.family_room
      state: 'on'
    - condition: numeric_state
      entity_id: light.family_room
      value_template: '{{ states.light.family_room.attributes.brightness }}'
      above: 100
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.family_room
        profile: "{{ states('sensor.preferred_light_profile') }}"


- alias: change master_bedroom light profile
  trigger:
    - platform: state
      entity_id: light.master_bedroom
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.next_sun_event
  condition:
    - condition: state
      entity_id: light.master_bedroom
      state: 'on'
    - condition: numeric_state
      entity_id: light.master_bedroom
      value_template: '{{ states.light.master_bedroom.attributes.brightness }}'
      above: 100
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.master_bedroom
        color_temp: "{{ states('sensor.preferred_light_color_temp') }}"
        brightness: "{{ states('sensor.preferred_light_brightness') }}"


#######################
# light schedules
#######################

# schedule example from Feb 5:
# wake     : 6:30 am
# dawn     : 6:48 am
# rising   : 7:19 am
# +1 hr    : 8:49 am
# noon     : 12:17 pm
# -1 hr    : 3:44 pm
# setting  : 5:14 pm
# dusk     : 5:45 pm
# -1 hr    : 11:17 am
# midnight : 12:17 am


- alias: fade on lights weekdays at 6:30am
  trigger:
    - platform: time
      at: '6:30:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_on
      data:
        color_temp: 443
        brightness: 1
        entity_id:
          - light.master_bedroom
    - service: light.turn_on
      data:
        color_temp: 156
        brightness: 254
        transition: 600
        entity_id:
          - light.master_bedroom
    - service: light.turn_on
      data:
        profile: relax
        brightness: 1
        entity_id:
          - light.family_room
          - light.living_room
          - light.outside
    - service: light.turn_on
      data:
        profile: energize
        brightness: 254
        transition: 600
        entity_id:
          - light.family_room
          - light.living_room
          - light.outside


- alias: fade on lights weekends at sunrise
  trigger:
    - platform: sun
      event: sunrise
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: light.turn_on
      data:
        color_temp: 443
        brightness: 1
        entity_id:
          - light.master_bedroom
    - service: light.turn_on
      data:
        color_temp: 156
        brightness: 254
        transition: 600
        entity_id:
          - light.master_bedroom
    - service: light.turn_on
      data:
        profile: relax
        brightness: 1
        entity_id:
          - light.family_room
          - light.living_room
          - light.outside
    - service: light.turn_on
      data:
        profile: energize
        brightness: 254
        transition: 600
        entity_id:
          - light.family_room
          - light.living_room
          - light.outside


- alias: turn off lights after sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: "+01:00:00"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.family_room
          - light.living_room
          - light.outside
          - light.master_bedroom


- alias: turn on lights before sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  action:
    - service: light.turn_on
      data_template:
        profile: "{{ states('sensor.preferred_light_profile') }}"
        entity_id:
          - light.family_room
          - light.living_room
          - light.outside


- alias: turn off lights before midnight
  trigger:
    - platform: time
      at: '23:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.family_room
          - light.living_room
          - light.outside