
#######################
# home and away
#######################


- alias: turn on vacuum when away
  trigger:
    platform: state
    entity_id: sensor.away_mode
    from: 'off'
    to: 'on'
  action:
    service: vacuum.turn_on
    entity_id: vacuum.consuela


- alias: turn off lights when away
  trigger:
    platform: state
    entity_id: sensor.away_mode
    from: 'off'
    to: 'on'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.master_bedroom
        - light.living_room
        - light.family_room


- alias: turn off vacuum when home
  trigger:
    platform: state
    entity_id: sensor.away_mode
    from: 'on'
    to: 'off'
  action:
    - service: vacuum.stop
      entity_id: vacuum.consuela
    - service: vacuum.return_to_base
      entity_id: vacuum.consuela


#######################
# wake and sleep
#######################


- alias: turn on lights weekdays at 6:30am
  trigger:
    platform: time
    at: '6:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_on
      data:
        entity_id: light.master_bedroom
        profile: energize
        transition: 900
    - service: light.turn_on
      data:
        entity_id: light.outside
        profile: concentrate


- alias: turn off lights at 11pm
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.family_room
        - light.living_room
        - light.outside


#######################
# sunrise and sunset
#######################


- alias: turn off lights at sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.family_room
        - light.living_room
        - light.outside


- alias: turn on lights at sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    data:
      entity_id: light.outside
      profile: concentrate


#######################
# motion and no motion
#######################


- alias: turn on lights when movement detected
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_camera_motion_detected
    to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: light.turn_on
    data:
      profile: read
      entity_id:
        - light.family_room
        - light.living_room


- alias: turn off lights 20 minutes after last movement detected
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_camera_motion_detected
    to: 'off'
    for:
      minutes: 20
  condition:
    condition: state
    entity_id: sensor.away_mode
    state: 'on'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.family_room
        - light.living_room
    