
#######################
# home and away
#######################


- alias: turn on vacuum when away
  trigger:
    - platform: state
      entity_id: sensor.away_mode
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: vacuum.consuela
      state: 'off'
  action:
    - service: vacuum.turn_on
      entity_id: vacuum.consuela


# - alias: turn off vacuum when home
#   trigger:
#     - platform: state
#       entity_id: sensor.away_mode
#       from: 'on'
#       to: 'off'
#   condition:
#     - condition: state
#       entity_id: vacuum.consuela
#       state: 'on'
#   action:
#     - service: vacuum.turn_off
#       entity_id: vacuum.consuela


- alias: turn off lights when away
  trigger:
    - platform: state
      entity_id: sensor.away_mode
      from: 'off'
      to: 'on'
  action:
    - service: script.turn_off_family_room_light
    - service: script.turn_off_living_room_light
    - service: script.turn_off_master_bedroom_light


- alias: turn on lights when home
  trigger:
    - platform: state
      entity_id: sensor.away_mode
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: script.turn_on_family_room_light
    - service: script.turn_on_living_room_light
    - service: script.turn_on_outside_light


#######################
# light profiles
#######################


- alias: change outside light profile
  trigger:
    - platform: state
      entity_id: light.outside
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.next_sun_event
  action:
    - service: script.change_outside_light_profile


- alias: change living_room light profile
  trigger:
    - platform: state
      entity_id: light.living_room
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.next_sun_event
  action:
    - service: script.change_living_room_light_profile


- alias: change family_room light profile
  trigger:
    - platform: state
      entity_id: light.family_room
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.next_sun_event
  action:
    - service: script.change_family_room_light_profile


- alias: change master_bedroom light profile
  trigger:
    - platform: state
      entity_id: light.master_bedroom
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: sensor.next_sun_event
  action:
    - service: script.change_master_bedroom_light_profile

#######################
# light schedules
#######################

# schedule example from Feb 5:
# wake     : 6:30 am
# dawn     : 6:48 am
# rising   : 7:19 am
# +1 hr    : 8:49 am
# noon     : 12:17 pm
# -1 hr    : 3:44 pm
# setting  : 5:14 pm
# dusk     : 5:45 pm
# -1 hr    : 11:17 am
# midnight : 12:17 am


- alias: fade on lights weekdays at 6:30am
  trigger:
    - platform: time
      at: '6:30:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: script.fade_on_master_bedroom_light
    - service: script.fade_on_family_room_light
    - service: script.fade_on_living_room_light
    - service: script.fade_on_outside_light


- alias: fade on lights weekends at sunrise
  trigger:
    - platform: sun
      event: sunrise
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: script.fade_on_family_room_light
    - service: script.fade_on_living_room_light
    - service: script.fade_on_outside_light


- alias: turn off lights after sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: "+01:00:00"
  action:
    - service: script.turn_off_family_room_light
    - service: script.turn_off_living_room_light
    - service: script.turn_off_outside_light


- alias: turn on lights before sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
  action:
    - service: script.turn_on_family_room_light
    - service: script.turn_on_living_room_light
    - service: script.turn_on_outside_light


- alias: turn off lights before midnight
  trigger:
    - platform: time
      at: '23:00:00'
  action:
    - service: script.turn_off_family_room_light
    - service: script.turn_off_living_room_light
    - service: script.turn_off_outside_light