
#######################
# home and away
#######################


- alias: turn on vacuum when away
  trigger:
    platform: state
    entity_id: sensor.away_mode
    from: 'off'
    to: 'on'
  action:
    service: vacuum.turn_on
    entity_id: vacuum.consuela


- alias: turn off inside lights when away
  trigger:
    platform: state
    entity_id: sensor.away_mode
    from: 'off'
    to: 'on'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.master_bedroom
        - light.living_room
        - light.family_room


- alias: turn off vacuum when home
  trigger:
    platform: state
    entity_id: sensor.away_mode
    from: 'on'
    to: 'off'
  action:
    - service: vacuum.stop
      entity_id: vacuum.consuela
    - service: vacuum.return_to_base
      entity_id: vacuum.consuela


- alias: turn on lights when home
  trigger:
    platform: state
    entity_id: sensor.away_mode
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.living_room
      {%- if now().hour >= 6 and now().hour < 12 %} # morning
      profile: energize
      {% elif now().hour >= 12 and now().hour < 18 %} # afternoon
      profile: concentrate
      {% elif now().hour >= 18 and now().hour < 24 %} # evening
      profile: read
      {% else %} # night
      profile: relax
      {%- endif %}


#######################
# time of day profiles
#######################


- alias: change light profiles at 6am
  trigger:
    platform: time
    at: '6:00:00'
  action:
    - service: light.turn_on
    data:
      entity_id:
        {%- if is_state('light.living_room', 'on') %}
        - light.living_room
        {%- endif %}
        {%- if is_state('light.family_room', 'on') %}
        - light.family_room
        {%- endif %}
        {%- if is_state('light.master_bedroom', 'on') %}
        - light.master_bedroom
        {%- endif %}
        {%- if is_state('light.outside', 'on') %}
        - light.outside
      profile: energize


- alias: change light profiles at 12pm
  trigger:
    platform: time
    at: '12:00:00'
  action:
    - service: light.turn_on
    data:
      entity_id:
        {%- if is_state('light.living_room', 'on') %}
        - light.living_room
        {%- endif %}
        {%- if is_state('light.family_room', 'on') %}
        - light.family_room
        {%- endif %}
        {%- if is_state('light.master_bedroom', 'on') %}
        - light.master_bedroom
        {%- endif %}
        {%- if is_state('light.outside', 'on') %}
        - light.outside
      profile: concentrate


- alias: change light profiles at 6pm
  trigger:
    platform: time
    at: '18:00:00'
  action:
    - service: light.turn_on
    data:
      entity_id:
        {%- if is_state('light.living_room', 'on') %}
        - light.living_room
        {%- endif %}
        {%- if is_state('light.family_room', 'on') %}
        - light.family_room
        {%- endif %}
        {%- if is_state('light.master_bedroom', 'on') %}
        - light.master_bedroom
        {%- endif %}
        {%- if is_state('light.outside', 'on') %}
        - light.outside
      profile: read


- alias: change light profiles at 12am
  trigger:
    platform: time
    at: '24:00:00'
  action:
    - service: light.turn_on
    data:
      entity_id:
        {%- if is_state('light.living_room', 'on') %}
        - light.living_room
        {%- endif %}
        {%- if is_state('light.family_room', 'on') %}
        - light.family_room
        {%- endif %}
        {%- if is_state('light.master_bedroom', 'on') %}
        - light.master_bedroom
        {%- endif %}
        {%- if is_state('light.outside', 'on') %}
        - light.outside
      profile: relax


#######################
# wake and sleep
#######################


- alias: fade on lights weekdays at 6:30am
  trigger:
    platform: time
    at: '6:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.master_bedroom
          - light.outside
        xy_color: 0.3146,0.3304 # energize
        brightness: 1
    - delay:
        seconds: 1
    - service: light.turn_on
      data:
        entity_id:
          - light.master_bedroom
          - light.outside
        xy_color: 0.3146,0.3304 # energize
        brightness: 254
        transition: 900 # 15 min


- alias: turn off lights at 11pm
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.family_room
        - light.living_room
        - light.outside


#######################
# sunrise and sunset
#######################


- alias: turn off all lights after sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:30:00" 
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.family_room
        - light.living_room
        - light.outside


- alias: turn on outside lights at sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.outside
        - light.living_room
      {%- if now().hour >= 6 and now().hour < 12 %} # morning
      profile: energize
      {% elif now().hour >= 12 and now().hour < 18 %} # afternoon
      profile: concentrate
      {% elif now().hour >= 18 and now().hour < 24 %} # evening
      profile: read
      {% else %} # night
      profile: relax
      {%- endif %}


# - alias: turn on inside lights before sunset if home
#   trigger:
#     platform: sun
#     event: sunset
#     offset: "-00:45:00" 
#   condition:
#     condition: state
#     entity_id: sensor.away_mode
#     state: 'off'
#   action:
#     service: light.turn_on
#     data:
#       entity_id:
#         - light.living_room
#         - light.family_room
#       {%- if now().hour >= 6 and now().hour < 12 %} # morning
#       profile: energize
#       {% elif now().hour >= 12 and now().hour < 18 %} # afternoon
#       profile: concentrate
#       {% elif now().hour >= 18 and now().hour < 24 %} # evening
#       profile: read
#       {% else %} # night
#       profile: relax
#       {%- endif %}


#######################
# motion and no motion
#######################


- alias: turn on lights when motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_camera_motion_detected
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen_camera_sound_detected
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen_camera_person_detected
      to: 'on'
  condition:
    # - condition: state
    #   entity_id: sensor.away_mode
    #   state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.family_room
      {%- if now().hour >= 6 and now().hour < 12 %} # morning
      profile: energize
      {% elif now().hour >= 12 and now().hour < 18 %} # afternoon
      profile: concentrate
      {% elif now().hour >= 18 and now().hour < 24 %} # evening
      profile: read
      {% else %} # night
      profile: relax
      {%- endif %}


- alias: turn off lights after last motion detected
  trigger:
    platform: time
    minutes: '/5' # check every 5 minutes
    seconds: 00
  condition:
    # - condition: state
    #   entity_id: sensor.away_mode
    #   state: 'on'
    - condition: state
      entity_id: binary_sensor.kitchen_camera_motion_detected
      state: 'off'
      for:
        minutes: 60
    - condition: state
      entity_id: binary_sensor.kitchen_camera_sound_detected
      state: 'off'
      for:
        minutes: 60
    - condition: state
      entity_id: binary_sensor.kitchen_camera_person_detected
      state: 'off'
      for:
        minutes: 60
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.family_room
