

# - platform: time_date
#   display_options:
#     - 'time'
#     - 'date'
#     - 'date_time'
#     - 'time_date'
#     - 'time_utc'
#     - 'beat'


- platform: yr
  name: Weather
  # forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature


- platform: template
  sensors:
    away_mode:
      value_template: "{{ states.climate.hallway.attributes.away_mode }}"


- platform: template
  sensors:
    next_sun_event:
      value_template: >-
        {% set next_time = 86400 %}
        {% if as_timestamp(states.sun.sun.attributes.next_noon) - as_timestamp(now()) < next_time %}
        {% set next_time = as_timestamp(states.sun.sun.attributes.next_noon) - as_timestamp(now()) %}
        {% set next_event = 'noon' %}
        {% endif %}
        {% if as_timestamp(states.sun.sun.attributes.next_setting) - as_timestamp(now()) < next_time %}
        {% set next_time = as_timestamp(states.sun.sun.attributes.next_setting) - as_timestamp(now()) %}
        {% set next_event = 'setting' %}
        {% endif %}
        {% if as_timestamp(states.sun.sun.attributes.next_dusk) - as_timestamp(now()) < next_time %}
        {% set next_time = as_timestamp(states.sun.sun.attributes.next_dusk) - as_timestamp(now()) %}
        {% set next_event = 'dusk' %}
        {% endif %}
        {% if as_timestamp(states.sun.sun.attributes.next_midnight) - as_timestamp(now()) < next_time %}
        {% set next_time = as_timestamp(states.sun.sun.attributes.next_midnight) - as_timestamp(now()) %}
        {% set next_event = 'midnight' %}
        {% endif %}
        {% if as_timestamp(states.sun.sun.attributes.next_dawn) - as_timestamp(now()) < next_time %}
        {% set next_time = as_timestamp(states.sun.sun.attributes.next_dawn) - as_timestamp(now()) %}
        {% set next_event = 'dawn' %}
        {% endif %}
        {% if as_timestamp(states.sun.sun.attributes.next_rising) - as_timestamp(now()) < next_time %}
        {% set next_time = as_timestamp(states.sun.sun.attributes.next_rising) - as_timestamp(now()) %}
        {% set next_event = 'rising' %}
        {% endif %}
        {{ next_event }}


- platform: template
  sensors:
    living_room_light_profile:
      value_template: >-
        {% if states.light.living_room.attributes.xy_color == [0.3146,0.3304] and states.light.living_room.attributes.brightness == 254 %}
        energize
        {% elif states.light.living_room.attributes.xy_color == [0.3682,0.3715] and states.light.living_room.attributes.brightness == 254 %}
        concentrate
        {% elif states.light.living_room.attributes.xy_color == [0.4452,0.4068] and states.light.living_room.attributes.brightness == 254 %}
        read
        {% elif states.light.living_room.attributes.xy_color == [0.5014,0.4153] and states.light.living_room.attributes.brightness == 144 %}
        relax
        {% else %}
        none
        {% endif %}


- platform: template
  sensors:
    family_room_light_profile:
      value_template: >-
        {% if states.light.family_room.attributes.xy_color == [0.3146,0.3304] and states.light.family_room.attributes.brightness == 254 %}
        energize
        {% elif states.light.family_room.attributes.xy_color == [0.3682,0.3715] and states.light.family_room.attributes.brightness == 254 %}
        concentrate
        {% elif states.light.family_room.attributes.xy_color == [0.4452,0.4068] and states.light.family_room.attributes.brightness == 254 %}
        read
        {% elif states.light.family_room.attributes.xy_color == [0.5014,0.4153] and states.light.family_room.attributes.brightness == 144 %}
        relax
        {% else %}
        none
        {% endif %}


- platform: template
  sensors:
    outside_light_profile:
      value_template: >-
        {% if states.light.outside.attributes.xy_color == [0.3146,0.3304] and states.light.outside.attributes.brightness == 254 %}
        energize
        {% elif states.light.outside.attributes.xy_color == [0.3682,0.3715] and states.light.outside.attributes.brightness == 254 %}
        concentrate
        {% elif states.light.outside.attributes.xy_color == [0.4452,0.4068] and states.light.outside.attributes.brightness == 254 %}
        read
        {% elif states.light.outside.attributes.xy_color == [0.5014,0.4153] and states.light.outside.attributes.brightness == 144 %}
        relax
        {% else %}
        none
        {% endif %}


- platform: template
  sensors:
    master_bedroom_light_profile:
      value_template: >-
        {% if states.light.master_bedroom.attributes.color_temp == 156 and states.light.master_bedroom.attributes.brightness == 254 %}
        energize
        {% elif states.light.master_bedroom.attributes.color_temp == 230 and states.light.master_bedroom.attributes.brightness == 254 %}
        concentrate
        {% elif states.light.master_bedroom.attributes.color_temp == 343 and states.light.master_bedroom.attributes.brightness == 254 %}
        read
        {% elif states.light.master_bedroom.attributes.color_temp == 443 and states.light.master_bedroom.attributes.brightness == 144 %}
        relax
        {% else %}
        none
        {% endif %}