
- platform: yr
  name: Weather
  # forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature
      
- platform: template
  sensors:
    away_mode:
      value_template: "{{ states.climate.hallway.attributes.away_mode }}"